DROP SEQUENCE BANINST1.Z_STU_ADVR_ZSADVR_SURROGATE_ID_SEQUENCE;

CREATE SEQUENCE BANINST1.Z_STU_ADVR_ZSADVR_SURROGATE_ID_SEQUENCE
  START WITH 6801
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


GRANT SELECT ON BANINST1.Z_STU_ADVR_ZSADVR_SURROGATE_ID_SEQUENCE TO USR_ADMIN_DEFAULT_M;

GRANT SELECT ON BANINST1.Z_STU_ADVR_ZSADVR_SURROGATE_ID_SEQUENCE TO USR_SS_DEFAULT_M;
