DROP SEQUENCE BANINST1.Z_STU_ADVR_MESSAGE_LOG_SEQ;

CREATE SEQUENCE BANINST1.Z_STU_ADVR_MESSAGE_LOG_SEQ
  START WITH 3206416
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


GRANT SELECT ON BANINST1.Z_STU_ADVR_MESSAGE_LOG_SEQ TO USR_ADMIN_DEFAULT_M;

GRANT SELECT ON BANINST1.Z_STU_ADVR_MESSAGE_LOG_SEQ TO USR_SS_DEFAULT_M;
