DROP TABLE BANINST1.Z_STU_ADVR_MESSAGE_LOG_TB CASCADE CONSTRAINTS;

CREATE TABLE BANINST1.Z_STU_ADVR_MESSAGE_LOG_TB
(
  MESSAGE_LOG_SEQ  NUMBER(22),
  CALLING_PROC     VARCHAR2(100 CHAR),
  CALLING_SECTION  VARCHAR2(100 CHAR),
  MESSAGE          VARCHAR2(256 CHAR),
  SQLCODE          NUMBER(22),
  SQLERRM          VARCHAR2(256 CHAR),
  USERNAME         VARCHAR2(30 CHAR),
  EXTERNAL_NAME    VARCHAR2(256 CHAR),
  OS_USER          VARCHAR2(30 CHAR),
  SESSION_USER     VARCHAR2(30 CHAR),
  CURRENT_USER     VARCHAR2(30 CHAR),
  PROXY_USER       VARCHAR2(30 CHAR),
  TERMINAL         VARCHAR2(64 CHAR),
  HOST             VARCHAR2(54 CHAR),
  IP_ADDRESS       VARCHAR2(30 CHAR),
  MESSAGE_DATE     DATE
);

ALTER TABLE BANINST1.Z_STU_ADVR_MESSAGE_LOG_TB ADD (
  PRIMARY KEY
  (MESSAGE_LOG_SEQ)
  USING INDEX
    TABLESPACE DEVELOPMENT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);


--  There is no statement for index BANINST1.SYS_C002107782.
--  The object is created when the parent object is created.

GRANT DELETE, INSERT, SELECT, UPDATE ON BANINST1.Z_STU_ADVR_MESSAGE_LOG_TB TO BANGUIDGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON BANINST1.Z_STU_ADVR_MESSAGE_LOG_TB TO BAN_DEFAULT_GUIDGEN_M;

GRANT SELECT ON BANINST1.Z_STU_ADVR_MESSAGE_LOG_TB TO SATURN;

GRANT DELETE, INSERT, SELECT, UPDATE ON BANINST1.Z_STU_ADVR_MESSAGE_LOG_TB TO USR_ADMIN_DEFAULT_M;

GRANT DELETE, INSERT, SELECT, UPDATE ON BANINST1.Z_STU_ADVR_MESSAGE_LOG_TB TO USR_DEFAULT_GUIDGEN_M;

GRANT DELETE, INSERT, SELECT, UPDATE ON BANINST1.Z_STU_ADVR_MESSAGE_LOG_TB TO USR_SS_DEFAULT_M;
